name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Runs on push to main branch
  pull_request:
    branches:
      - main # Runs on pull requests to main branch

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Set Node.js version compatible with your Next.js app

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Next.js app
        run: npm run build

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: ci # Runs this job only if the CI job is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Set this token in your GitHub secrets
        run: npx vercel --prod --token=$VERCEL_TOKEN
